'use client';
import {useEffect,useRef,useState} from 'react';import {isAndroidApp,syncAndroid,requestAndroidNotifications} from '@/lib/android';import {Home,Grid2X2,Sun,ChartNoAxesColumn,Settings,Menu,X,Leaf,Check,Info,Trophy} from 'lucide-react';
import {CourseState,STORAGE_KEY,courseDay,initialState,localDate,pepperCount,pepperLabel,validState} from '@/lib/course';import {HomeScreen} from '@/components/course/HomeScreen';import {TodayCard} from '@/components/course/TodayCard';import {CourseGrid} from '@/components/course/CourseGrid';import {StatisticsScreen} from '@/components/course/StatisticsScreen';import {SettingsScreen} from '@/components/course/SettingsScreen';
type Screen='home'|'today'|'course'|'stats'|'settings';type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
const tabs=[{id:'home' as Screen,label:'Главная',Icon:Home},{id:'today' as Screen,label:'Сегодня',Icon:Sun},{id:'course' as Screen,label:'Весь курс',Icon:Grid2X2},{id:'stats' as Screen,label:'Статистика',Icon:ChartNoAxesColumn}];
export default function App(){const [state,setState]=useState<CourseState>(initialState);const [ready,setReady]=useState(false);const [screen,setScreen]=useState<Screen>('home');const [now,setNow]=useState(new Date());const [menu,setMenu]=useState(false);const [toast,setToast]=useState('');const [reset,setReset]=useState(false);const [selected,setSelected]=useState<number|null>(null);const [installHelp,setInstallHelp]=useState(false);const installRef=useRef<InstallPrompt|null>(null);const stateRef=useRef(state);const notificationBusy=useRef(false);const day=courseDay(state.startDate,now);const progress=Math.round(state.completed.length/30*100);const done=state.completed.includes(day);
const message=(text:string)=>setToast(text);
function save(next:CourseState){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));stateRef.current=next;setState(next);if(isAndroidApp())syncAndroid(next);return true;}catch{message('Не удалось сохранить данные. Проверьте доступ к памяти браузера.');return false;}}
const patch=(changes:Partial<CourseState>)=>save({...stateRef.current,...changes});
useEffect(()=>{const initTimer=setTimeout(()=>{try{const raw=localStorage.getItem(STORAGE_KEY)||(isAndroidApp()?window.PepperAndroid?.getState():null);const loaded=raw?validState(JSON.parse(raw)):initialState();stateRef.current=loaded;setState(loaded);if(isAndroidApp())syncAndroid(loaded);}catch{setToast('Сохраненные данные недоступны. Проверьте настройки браузера.');}setReady(true);},0);if(!isAndroidApp())navigator.serviceWorker?.register('/sw.js').catch(()=>{});const timer=setInterval(()=>setNow(new Date()),15000);const sync=()=>{setNow(new Date());try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const loaded=validState(JSON.parse(raw));stateRef.current=loaded;setState(loaded);}}catch{}};const install=(e:Event)=>{e.preventDefault();installRef.current=e as InstallPrompt;};window.addEventListener('storage',sync);window.addEventListener('focus',sync);window.addEventListener('beforeinstallprompt',install);return()=>{clearTimeout(initTimer);clearInterval(timer);window.removeEventListener('storage',sync);window.removeEventListener('focus',sync);window.removeEventListener('beforeinstallprompt',install);};},[]);
useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);},[toast]);
useEffect(()=>{if(isAndroidApp()||!ready||!state.notifications||day<1||day>30||done||notificationBusy.current||!('Notification' in window)||Notification.permission!=='granted')return;const dateKey=`${state.startDate}:${localDate(now)}`;const [h,m]=state.time.split(':').map(Number);const due=state.snoozeUntil?now.getTime()>=state.snoozeUntil:now.getHours()*60+now.getMinutes()>=h*60+m;if(!due||state.notified.includes(dateKey))return;notificationBusy.current=true;(async()=>{try{const reg=await navigator.serviceWorker.ready;const latest=stateRef.current;if(latest.completed.includes(day)||!latest.notifications||latest.startDate!==state.startDate)return;await reg.showNotification(`Сегодня день ${day} — отметьте выполнение курса`,{body:day===30?'Завершение выбранного курса':pepperLabel(pepperCount(day)),icon:'/icon-192.png',tag:dateKey,silent:!latest.sound});save({...latest,notified:[...latest.notified,dateKey],snoozeUntil:null});}catch{message('Браузер не смог показать уведомление.');}finally{notificationBusy.current=false;}})();},[now,state,day,done,ready]);
function complete(){const latest=stateRef.current;const current=courseDay(latest.startDate);if(current<1||current>30||latest.completed.includes(current))return;if(save({...latest,completed:[...latest.completed,current],snoozeUntil:null})){message(current===30?'Завершение курса отмечено':'Сегодняшний день отмечен. Отличный шаг!');if(!isAndroidApp())navigator.serviceWorker?.ready.then(async reg=>{for(const n of await reg.getNotifications())n.close();}).catch(()=>{});}}
async function enable(){if(isAndroidApp()){const granted=await requestAndroidNotifications();if(granted){patch({notifications:true});message('Напоминания включены');}else message('Разрешите уведомления в настройках Android.');return granted;}if(!('Notification' in window)||!navigator.serviceWorker){message('Этот браузер не поддерживает уведомления.');return false;}try{const permission=await Notification.requestPermission();if(permission==='granted'){patch({notifications:true});message('Напоминания включены');return true;}message('Разрешите уведомления в настройках браузера.');}catch{message('Уведомления недоступны в этом браузере.');}return false;}
async function snooze(){if(done||day<1||day>30)return;if(!stateRef.current.notifications&&!(await enable()))return;const key=`${stateRef.current.startDate}:${localDate()}`;patch({snoozeUntil:Date.now()+3600000,notified:stateRef.current.notified.filter(k=>k!==key)});message(isAndroidApp()?'Напомним примерно через час.':'Напомним через час, если приложение открыто.');}
const navigate=(id:Screen)=>{setScreen(id);setMenu(false);window.scrollTo({top:0,behavior:'smooth'});};
async function install(){if(isAndroidApp()){message('Приложение уже установлено');return;}if(installRef.current){await installRef.current.prompt();await installRef.current.userChoice;installRef.current=null;}else setInstallHelp(true);}
return <div className="app-shell"><header className="app-header"><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('home')}}><span className="brand-icon"><Leaf size={22}/></span><span>Курс перца <em>горошек</em></span></a><nav className="desktop-nav" aria-label="Основная навигация">{tabs.map(({id,label,Icon})=><button className={screen===id?'active':''} key={id} onClick={()=>navigate(id)}><Icon size={17}/>{label}</button>)}</nav><div className="header-actions"><span className="header-caption">30 дней · ваш ритм</span><button className={`icon-button ${screen==='settings'?'active':''}`} aria-label="Настройки" onClick={()=>navigate('settings')}><Settings size={20}/></button><button className="icon-button menu-button" aria-label="Открыть меню" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={21}/>:<Menu size={21}/>}</button></div></header>
{menu&&<nav className="menu-panel" aria-label="Меню">{[...tabs,{id:'settings' as Screen,label:'Настройки',Icon:Settings}].map(({id,label,Icon})=><button key={id} onClick={()=>navigate(id)}><Icon size={18}/>{label}</button>)}</nav>}
<main>{!ready?<div className="loading">Загружаем ваш курс…</div>:<div key={screen} className="screen-enter">{screen==='home'&&<HomeScreen day={day} completed={state.completed} onComplete={complete} onSnooze={snooze} onCourse={()=>navigate('course')} onSelect={setSelected}/>}{screen==='today'&&<section className="screen today-screen"><div className="section-heading"><div><p className="eyebrow">В СВОЕМ РИТМЕ</p><h1>Ваш сегодняшний шаг</h1></div></div><TodayCard day={day} done={done} progress={progress} onComplete={complete} onSnooze={snooze} expanded/><p className="next-day">{day<29?`Завтра — ${pepperLabel(pepperCount(Math.max(1,day+1)))}`:day===29?'Завтра — завершение курса':'Каждая отметка имеет значение'}</p></section>}{screen==='course'&&<section className="screen"><div className="section-heading"><div><p className="eyebrow">30 МАЛЕНЬКИХ ШАГОВ</p><h1>Весь курс</h1><p className="muted">От первого дня до завершения. В вашем темпе.</p></div><span className="pill">{state.completed.length} / 30</span></div><CourseGrid day={day} completed={state.completed} onSelect={setSelected}/><div className="overview-summary"><span><i className="green"/>Выполнено</span><span><i className="outline"/>Сегодня</span><span><i/>Впереди</span></div></section>}{screen==='stats'&&<StatisticsScreen completed={state.completed} day={day}/>}{screen==='settings'&&<SettingsScreen state={state} onChange={patch} onEnable={enable} onReset={()=>setReset(true)} onInstall={install}/>}</div>}</main>
<footer className="desktop-footer"><span><Leaf size={14}/> Маленькие шаги, день за днем.</span><span>Личный трекер привычки</span></footer><nav className="bottom-nav" aria-label="Навигация по экранам">{tabs.map(({id,label,Icon})=><button className={screen===id?'active':''} key={id} onClick={()=>navigate(id)}><Icon size={21}/><span>{label}</span></button>)}</nav>{toast&&<div role="status" className="toast"><Check size={18}/>{toast}</div>}
{(reset||selected!==null||installHelp)&&<div className="modal-backdrop" onClick={()=>{setReset(false);setSelected(null);setInstallHelp(false)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="Закрыть" onClick={()=>{setReset(false);setSelected(null);setInstallHelp(false)}}><X/></button>{reset?<><h2 id="modal-title">Начать курс заново?</h2><p>Все 30 отметок будут удалены. Курс начнется сегодня. Это действие нельзя отменить.</p><button className="complete-button" onClick={()=>{if(save({...initialState(),notifications:state.notifications,time:state.time,sound:state.sound})){setReset(false);message('Начат новый курс');}}}>Да, сбросить прогресс</button><button className="snooze-button" onClick={()=>setReset(false)}>Отмена</button></>:installHelp?<><h2 id="modal-title">Приложение на телефоне</h2><p>В Chrome на Android откройте меню ⋮ и выберите «Установить приложение» или «Добавить на главный экран».</p><p className="muted">После первого открытия приложение доступно без интернета. Отметки хранятся в этом браузере.</p></>:<><span className="eyebrow">ВАШ КУРС</span><h2 id="modal-title">День {selected}</h2><div className="modal-dose">{selected===30?<Trophy/>:pepperLabel(pepperCount(selected!))}</div><p>{state.completed.includes(selected!)?'Этот день выполнен':selected===day?'Ваш сегодняшний шаг':selected!>day?'Этот день еще впереди':'Этот день не отмечен'}</p>{selected===30&&<p className="muted">День завершения, без горошин.</p>}{selected===day&&!done&&<button className="complete-button" onClick={()=>{complete();setSelected(null)}}><Check/> {day===30?'Завершить курс':'Я принял(а)'}</button>}<p className="setting-note"><Info size={14}/> Отметить можно только текущий день.</p></>}</section></div>}</div>;}
