plugins { id 'com.android.application' }
android {
 namespace 'ru.peppercourse.tracker'
 compileSdk 35
 defaultConfig { applicationId 'ru.peppercourse.tracker'; minSdk 26; targetSdk 35; versionCode 110; versionName '1.1.0' }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
 buildTypes { release { minifyEnabled false; signingConfig signingConfigs.debug } }
}
dependencies { implementation 'androidx.webkit:webkit:1.12.1' }
